### ISSUE TITLE
Any way to support horizontal bar charts?

### ISSUE THREAD

**Issue by dchuk** [airblade/chartjs-ror#10]
Thanks for creating such an easy to use plugin! Was curious if there was a way to facilitate supporting horizontal bar charts similar to how this is implemented here: https://github.com/tomsouthall/Chart.HorizontalBar.js

Even if you could point me in the right direction to enabling this myself would be much appreciated.

**Comment by airblade** [comment]
Something like this might work:

- Fork the repo.
- Add the horizontal bar chart js to `/vendor/assets/javascripts/`.
- Add the new chart [here](https://github.com/airblade/chartjs-ror/blob/722902c803a0cc7877c7f9e56bc6dd4d84b0af69/lib/chartjs/chart_helpers.rb#L4).

**Comment by agungyuliaji** [comment]
cool! i need that bar for my project! after i add horizontal bar feature.
is allowed to make pull request to your repo? @airblade

**Comment by airblade** [comment]
I'm not going to add any charts not built into Chart.js, but I would be happy to add a general way to load up any extra charts the users specifies somehow.

**Comment by lxchavez** [comment]
@airblade tried your suggestions and received a js error on the browser console status stating:

> index:91 Uncaught TypeError: (intermediate value).HorizontalBar is not a function

`var chart = new Chart(ctx).HorizontalBar(data, opts);`

Has anyone gotten this to work or have any suggestions?

**Comment by airblade** [comment]
I'm not sure what the problem is; the first step would be to determine whether it's in Ruby-land or Javascript.  Can you see your bar chart function at all in the js console?

**Comment by lxchavez** [comment]
Problem ended up being in Ruby-land. Got it to work by adding `//= require Chart.HorizontalBar` to application.js under `app/assets/javascripts` of my rails app.

**Comment by airblade** [comment]
@lxchavez That makes sense.  Thanks for reporting back.

**Comment by yoseppiedro** [comment]
I'm so sorry but I still didn't understand, i'm beginner on rails and chart.js..
So, can I use your built in helper to use Horizontal Bar?

@lxchavez can you explain me more about how you could got it work and how to implement it?

**Comment by airblade** [comment]
@yoseppiedro Horizontal bar charts are now (as of [v3.0.1](https://github.com/airblade/chartjs-ror/releases/tag/v3.0.1)) supported out of the box.  Use this in your Rails views:

```ruby
= horizontal_bar_chart data, options
```

**Comment by yoseppiedro** [comment]
Thank you so much, you save my day @airblade
