### ISSUE TITLE
hook into onAnimationComplete event

### ISSUE THREAD

**Issue by nicpillinger** [airblade/chartjs-ror#11]
hi - thanks for the gem, i'm managing to get most of what I want done but I cant seem to hook into the onAnimationComplete event. Have you got any idea how I can achieve this? Presumably this is the only way to know the chart is complete and exists at window.Chart[id] ?? 

if I pass some js through options it just fails to call the function eg. 
onAnimationComplete: j('function(){alert("hello!");};')

**Comment by nicpillinger** [comment]
I've got a patch for it - will create a PR

**Comment by airblade** [comment]
Closed by2924d3f.
