### ISSUE TITLE
Uncaught TypeError: Cannot read property 'draw' of undefined

### ISSUE THREAD

**Issue by vinimxit** [airblade/chartjs-ror#13]
![line](https://cloud.githubusercontent.com/assets/7932334/7830333/d54b15c0-0469-11e5-91d6-3586163999bb.PNG)

The format of my data is as above however i am getting the error. Please help.

**Comment by airblade** [comment]
I'll be able to look at this when I get back from holiday...

Usually this kind of problem is due to there being an extra object in the hierarchy, or something similar.

**Comment by airblade** [comment]
@vinimxit Did you get this working?

**Comment by airblade** [comment]
Your data format looks ok to me.  Are you still having problems with this?

**Comment by airblade** [comment]
Were you loading your chart via AJAX?

**Comment by airblade** [comment]
Closing this because it's gone quiet and I've upgraded the plugin ([v3.0.0](https://github.com/airblade/chartjs-ror/releases/tag/v3.0.0)) to use Chart.js v2.1.4, which has different data and options formats.
