### ISSUE TITLE
How to show label on tooltip

### ISSUE THREAD

**Issue by poc7667** [airblade/chartjs-ror#14]
I want to show each dataset's label in tooltip,

I don't get what do you mean on the README.md

Which file should I modify ?  `vendor/assets/javascripts/Chart.js` ???

                  label: dataset[:type],
                  pointHighlightStroke: "#{color}",
                  data: dataset[:data]

**Comment by airblade** [comment]
You shouldn't need to modify any files; you specify the `tooltipTemplate` option as per the Chart.js docs.

Sorry I can't be of more help right now; I'm away on holiday.  I'll get back to you when I return.

**Comment by airblade** [comment]
@poc7667 Did you get this working?
