### ISSUE TITLE
Hi, Is there a way for me to use getPointsAtEvent while still using the Gem.

### ISSUE THREAD

**Issue by sonuoommen** [airblade/chartjs-ror#16]
I am able to get points when I use javascript  and define the chart that way. I want to know if there is a way I can do it as it is intended using your gem.

**Comment by airblade** [comment]
You can get hold of the chart object either via the DOM element, which has a known id if you pass it in to the chart helper, or via the `window` object.

**Comment by sonuoommen** [comment]
can you give an example ? perhaps the code.

**Comment by airblade** [comment]
In your Rails view, e.g ERB:

```erb
<%= bar_chart your_data, {id: 'mychart'} %>
```

In your Coffeescript:

```coffee
$ ->
  $('#mychart').on 'click', (evt) ->
    chart = window.Chart[evt.target.id]
    activePoints = chart['getPointsAtEvent'](evt)
```

**Comment by sonuoommen** [comment]
Cool, Thanks.

**Comment by AKovtunov** [comment]
@airblade good day! Is something changed here?
window.Chart[evt.target.id] returns nil for me.
How can I patch this method to make `getPointsAtEvent` working?

**Comment by airblade** [comment]
What version of the gem are you using?  Version 3.0 (specifically commit 97e15b) stopped storing the chart in `window.Chart`.

**Comment by AKovtunov** [comment]
@airblade yep, I've noticed. I'm using the latest one. Is there any other way to get pie chart segment's value or name by clicking on segment in the latest version?

**Comment by airblade** [comment]
I think you should be able to do it by specifying `onClick` handlers when you set up your chart.
