### ISSUE TITLE
undefined method `no_confict!' for Chartjs:Module

### ISSUE THREAD

**Issue by austinarchibald** [airblade/chartjs-ror#22]
As README says, I added: 

```ruby
# config/initializers/chartjs.rb
Chartjs.no_confict!
```

But I get `undefined method `no_confict!' for Chartjs:Module (NoMethodError)`? File is correctly place, lines added to application.js. Server won't load. Was trying to add this to remove any conflict with chartkick.

**Comment by airblade** [comment]
That's weird.  Are you on the latest version of chartjs-ror?  What version of Rails are you running?

**Comment by austinarchibald** [comment]
using chartjs-ror 2.2.0 & Rails 4.2.2

**Comment by b1592** [comment]
This may already been addressed elsewhere, but it seems to be a typo in the readme:
    
    # config/initializers/chartjs.rb
    Chartjs.no_conflict!
should do it!

**Comment by austinarchibald** [comment]
lol... I honestly had to look at what you typed for like 30 seconds, thinking to myself, it's exactly what I have in my initializer...  hahaha that l is hard to spot!

Thank you!

**Comment by airblade** [comment]
Sorry about that!  Well spotted @b1592.

It's fixed in 79f28cfd.
