### ISSUE TITLE
there is a way to use custom created chart?

### ISSUE THREAD

**Issue by davidesantangelo** [airblade/chartjs-ror#25]

**Comment by airblade** [comment]
Sorry, I don't understand what you're asking.

**Comment by davidesantangelo** [comment]
I just created a new chart called DoghnutAlt and i want use the associated helper like doghnut_alt_chart. There is a way to use a custom chart with the helper methods. Thanks

**Comment by airblade** [comment]
Thanks for the clarification.

There's isn't yet a built-in way to use custom charts, but the workaround in #10 should work.

**Comment by davidesantangelo** [comment]
Thanks!

**Comment by airblade** [comment]
This plugin now supports Chart.js v2.1.4 so it might be easier to use custom charts now.
