### ISSUE TITLE
Pie, Doughnut, and Polar charts not working.

### ISSUE THREAD

**Issue by Anyoks** [airblade/chartjs-ror#28]
Hallo.

I have a strange problem. My Pie, doughtnut and Polar charts aren't receiving data therefore they don't render.

This is the controller code.

```
@data = {
      labels: "May",
      datasets: [
        {
           data: 4
           backgroundColor: "#FF6384",
           hoverBackgroundColor: "#FF6384"

        }
      ]
    }
@options = {}
```

Here's the view:

` = pie_chart @data, @options `

I don't get any errors at all. And the Javascript code doesn't have the datasets as do the others (line chart etc). The other charts work properly. Any idea on what might be the problem?

Below is a screenshot of a working chart js, it has the `datasets` attribute that is missing in the three charts that don't work.

![image](https://cloud.githubusercontent.com/assets/1647681/15541689/4f599f08-2296-11e6-967d-11eedbd8c90e.png)

Thanks for your assistance!

**Comment by airblade** [comment]
Do the values for `data`, `backgroundColor` and `hoverBackgroundColor` need to be arrays?

**Comment by Anyoks** [comment]
That's what Chartjs says. See,
```
var data = {
    labels: [
        "Red",
        "Green",
        "Yellow"
    ],
    datasets: [
        {
            data: [300, 50, 100],
            backgroundColor: [
                "#FF6384",
                "#36A2EB",
                "#FFCE56"
            ],
            hoverBackgroundColor: [
                "#FF6384",
                "#36A2EB",
                "#FFCE56"
            ]
        }]
};
```

**Comment by airblade** [comment]
Exactly.  The controller code you posted doesn't use arrays for the values.

**Comment by Anyoks** [comment]
Sorry, actually it does, I replaced the values quickly and forgot to add the arrays. This is the right code. It still doesn't work.


```
@data = {
      labels: "May",
      datasets: [
        {
           data: 4
           backgroundColor: "#FF6384",
           hoverBackgroundColor: "#FF6384"

        }
      ]
    }
@options = {}
```

**Comment by airblade** [comment]
Sorry to go on about arrays but it's still not clear to me whether this works or not:

```ruby
@data = {
      labels: ["May"],
      datasets: [
        {
           data: [4]
           backgroundColor: ["#FF6384"],
           hoverBackgroundColor: ["#FF6384"]
        }
      ]
    }
@options = {}
```

**Comment by covard** [comment]
@airblade it doesn't look like the array works. I have been trying to get the bar chart to change color and it stays this gray color.

![screen shot 2016-05-31 at 10 59 04 am](https://cloud.githubusercontent.com/assets/633250/15683264/b813d4fa-271e-11e6-8e3b-f5f5f07ebade.png)


```ruby
@graph_data_amounts = {
        labels: investments_hsh.keys,
        datasets: [
          {
            label: "Investment Amounts Per Month",
            backgroundColor: ["#FF6384"],
           hoverBackgroundColor: ["#FF6384"],
            data: investments_hsh.values
          }
        ]
      }
```

**Comment by covard** [comment]
I am also having the same issue. Pie chart isn't showing up.

```ruby
@graph_data_categories = {
        labels: ["BioTech", "Consumer Goods"],
        datasets: [
          {
            backgroundColor: ["#FF6384", "#36A2EB"],
            hoverBackgroundColor: ["#FF6384", "#36A2EB"],
            data: [4, 2]
          }
        ]
      }
```

![screen shot 2016-06-01 at 2 55 32 pm](https://cloud.githubusercontent.com/assets/633250/15725409/fea890be-2808-11e6-87bb-dd78b86bdf61.png)

**Comment by covard** [comment]
@Anyoks did you ever get the pie charts to work for you?

**Comment by airblade** [comment]
I'm away this week but will take a look when I'm back.

BTW the plugin isn't using Chart.js 2 yet...

**Comment by Anyoks** [comment]
@airblade the pie chart with `data: [4]` as you asked doesn't work.
Seems to me that @covard  has the exact problem as I do. 
@covard  Not yet. The pie chart doesn't show up. It's so strange. Did you get a solution? I'm kinda stuck.

**Comment by covard** [comment]
@airblade ok great thanks for work on this gem.

@Anyoks no for now I'm just hiding the pie chart until it's working.

**Comment by airblade** [comment]
I think the problem is that pie charts need the data in a different format from line charts.

Looking at the [pie chart docs for v1.0.2](https://github.com/chartjs/Chart.js/blob/v1.0.2/docs/05-Pie-Doughnut-Chart.md), `data` needs to look like:

```
var data = [
    {
        value: 300,
        color:"#F7464A",
        highlight: "#FF5A5E",
        label: "Red"
    },
    {
        value: 50,
        color: "#46BFBD",
        highlight: "#5AD3D1",
        label: "Green"
    },
    {
        value: 100,
        color: "#FDB45C",
        highlight: "#FFC870",
        label: "Yellow"
    }
]
```

This is different from the [v2 format](https://github.com/chartjs/Chart.js/blob/v2.1.4/docs/07-Pie-Doughnut-Chart.md).

I think if you change your data format around the pie chart will work.

In the meantime I'm going to upgrade the Chart.js bundled with this gem (so you won't need to change around your data).

**Comment by airblade** [comment]
I've upgraded the plugin ([v3.0.0](https://github.com/airblade/chartjs-ror/releases/tag/v3.0.0)) to use Chart.js v2.1.4 – which should make your code work now.

Let me know if you still have problems and I'll reopen this issue.

**Comment by Anyoks** [comment]
Hey! Thanks a lot. All charts work like a charm!

But, I get an `undefined method "pie_chart" for #<#<Class:0x007f86444ec538>:0x007f8644fcbb70>`
for some strange reason. Did you change the method used to call the pie_chart?

![undefined](https://cloud.githubusercontent.com/assets/1647681/16001721/69535aa0-315c-11e6-9179-7b6beab5ab41.png)

**Comment by airblade** [comment]
@Anyoks Oops, I overlooked the pie chart.  It's restored in v3.0.2.
