### ISSUE TITLE
Provide a CHANGELOG

### ISSUE THREAD

**Issue by sgringwe** [airblade/chartjs-ror#29]
Hello! I noticed you bumped the major version of this gem. Would you be willing to provide a CHANGELOG file with details on what caused the major version bump?

**Comment by airblade** [comment]
Here it is: 36dfa50.

The major version bump was due to upgrading Chart.js from v1.0.2. to v2.1.4.  Chart.js's data and options have changed in a backwards-incompatible way, and IE8 and below are no longer supported.

**Comment by sgringwe** [comment]
Thanks!
