### ISSUE TITLE
Default legend not rendering

### ISSUE THREAD

**Issue by bcackerman** [airblade/chartjs-ror#3]
It seems that a legend is trying to be rendered: http://cl.ly/image/2T0w400U2Y39  But is just resulting in two list dots. 

I'm using your default data with this helper `= line_chart @labels, @datasets, {width: 800, height: 400, responsive: true}`

If I use these options, there is no 'legend' `= line_chart @labels, @datasets, {width: 800, height: 400, responsive: true, legendTemplate: " "}`

**Comment by airblade** [comment]
I've just pushed 4dfc6cd to fix this.

- No legend is generated by default.
- Pass `generateLegend: true` in your options if you do want a legend.
- Optionally specify a custom legend template with the `legendTemplate: <...>` option.
