### ISSUE TITLE
new chart undefined 

### ISSUE THREAD

**Issue by ChrisCPO** [airblade/chartjs-ror#30]
using rails 3.2 not sure if that matters here, but looks like it's not finding the Chart js code. 
calling via

``` ruby
= horizontal_bar_chart(assessment.chart_data, {})
```

edit:54 Uncaught ReferenceError: Chart is not definedinitChart @ edit:54

**Comment by airblade** [comment]
I use this with Rails 3.2 so it's some other problem.

Have you got this in your `application.js`?

```
//= require Chart.min
```

**Comment by airblade** [comment]
Assuming this is solved...
