### ISSUE TITLE
Can you format decimals to become currency values?

### ISSUE THREAD

**Issue by RailsCod3rFuture** [airblade/chartjs-ror#44]
I'm currently using chartkick gem, but its not allowing me to turn large decimals into formatted money objects. I see 2500000 instead of $25,000 on the column_chart, and the chart itself only allows me to go from $0 to $1 using the thousands: "," prefix: "$". Do you know how to remedy this issue? Does the gem allow formatting for decimal numbers?

**Comment by airblade** [comment]
Chartkick is not related to this gem.

It sounds like you need to format the labels yourself and pass them into your chart function to use instead of its automatically generated labels.  You could use a snippet like this to format the numbers:

```javascript
value.toString().replace((/\B(?=(\d{3})+(?!\d))/g, ',')
```

**Comment by RailsCod3rFuture** [comment]
Thanks.
