### ISSUE TITLE
labels: 3rd value becomes a "-"

### ISSUE THREAD

**Issue by Andy-Post** [airblade/chartjs-ror#49]
Hey there,
I've a problem with showing the "labels" on doughnut-charts.
If I only have 2 values - labels are shown correctly, but if I have more than 2 values for the 'labels' attribute the third value becomes a: "-"
![dougnut_canvas_labelproblem](https://user-images.githubusercontent.com/42770962/50584090-907f5980-0e6d-11e9-8127-2152c45fe402.png)

I collect the values via PHP in my var '$close1', when I do a print_r($close1) I get:
["customer", "fb", "colo", "isam", "reseller"] 
...but in chartJS-script I've the following values:
["customer", "fb", "-", "colo", "isam"]

...what can I do?

**Comment by airblade** [comment]
If you're using PHP, how are you using this Rails plugin?

**Comment by Andy-Post** [comment]
....damn. Posted in wrong git...2019 starts more worse than 2018 ends.
I'm sorry ;)
