### ISSUE TITLE
Can't import

### ISSUE THREAD

**Issue by cejaramillof** [airblade/chartjs-ror#55]
When, i'm import da gem, i get this error:
couldn't find file 'Chart.bundle.min' with type 'application/javascript'
or
couldn't find file 'Chart.min' with type 'application/javascript'

please can help me?

**Comment by Monza** [comment]
I know it is old post but for new people searching.

You might have forgot to restart the web server.

**Comment by zhum** [comment]
Nope... I've stopped webserver and run `bundle exec rake assets:precompile` and got the same problem.
