### ISSUE TITLE
:element_id option doesn't work.

### ISSUE THREAD

**Issue by DylanDavidson** [airblade/chartjs-ror#8]
I was trying to utilize the `:element_id` option you mention in the README, but it wasn't working.

I dug into the code and I found this in [`chart_helpers.rb`](https://github.com/airblade/chartjs-ror/blob/master/lib/chartjs/chart_helpers.rb#L15):

``` ruby
element_id = options.delete(:id)     || "chart-#{@chart_id += 1}"
```

It looks like the `:id` option will work the way `:element_id` was intended to work.

The way I see it, there are 3 possible options to fix this:
- Update the README to reflect the true option
```
`:id` - id of the `<canvas/>` - default is `chart-n` where `n` is the 0-based index of the chart on the page.        
```
- Deprecate the `:id` option, and replace it with `:element_id` like it says in README
``` ruby
element_id = options.delete(:element_id) || "chart-#{@chart_id += 1}"
```
- Provide backwards compatibility with `:id` and support `:element_id` and possibly deprecate `:id` in the future
``` ruby
element_id = options.delete(:id) || options.delete(:element_id) || "chart-#{@chart_id += 1}"
```

I'd be happy to submit a pull-request with any of the above mentioned changes, I just wanted to see what was the preferred option first.

**Comment by airblade** [comment]
Oops, thanks for pointing this out.

I think updating the README would suffice: the code itself is ok and anybody who had tried to use `:element_id` would have found it didn't work.
